name: Build Windows EXE

on:
  push:
    branches: [ "main", "deploy/*" ]
    paths:
      - 'autohdr_client_exe/**'
      - 'autohdr_client_exe_v2/**'
  workflow_dispatch:

jobs:
  # job build cho bản V1
  build_v1:
    runs-on: windows-latest
    steps:
    - name: Tải Code vào môi trường Build
      uses: actions/checkout@v4

    - name: Cài đặt Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cài đặt Thư viện và PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r autohdr_client_exe/requirements.txt

    - name: Đóng gói thành file chạy (.exe)
      working-directory: ./autohdr_client_exe
      run: |
        pyinstaller --onefile --noconsole --name AutoHDR_v1 main.py

    - name: Lưu trữ và gửi file cài đặt v1
      uses: actions/upload-artifact@v4
      with:
        name: AutoHDR_v1
        path: autohdr_client_exe/dist/AutoHDR_v1.exe
        retention-days: 7

  # job build cho bản V2
  build_v2:
    runs-on: windows-latest
    steps:
    - name: Tải Code vào môi trường Build
      uses: actions/checkout@v4

    - name: Cài đặt Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cài đặt Thư viện và PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r autohdr_client_exe_v2/requirements.txt

    - name: Đóng gói thành file chạy (.exe)
      working-directory: ./autohdr_client_exe_v2
      run: |
        pyinstaller --onefile --noconsole --name AutoHDR_v2 main.py

    - name: Lưu trữ và gửi file cài đặt v2
      uses: actions/upload-artifact@v4
      with:
        name: AutoHDR_v2
        path: autohdr_client_exe_v2/dist/AutoHDR_v2.exe
        retention-days: 7
