name: Build Windows EXE

# Hành động này tự động chạy khi bạn có thay đổi code và đẩy (push) lên GitHub 
# ở các branch: 'main' hoặc các nhánh bắt đầu bằng 'deploy/'
# Ngoài ra bạn cũng có thể tự qua trang Github Action tự bấm chạy (workflow_dispatch)
on:
  push:
    branches: [ "main", "deploy/*" ]
    paths:
      - 'autohdr_client_exe/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Tải Code vào môi trường Build
      uses: actions/checkout@v4

    - name: Cài đặt Python trên Windows Ảo
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Ổn định và tương thích tốt nhất

    - name: Cài đặt Thư viện và PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r autohdr_client_exe/requirements.txt

    - name: Đóng gói thành file chạy (.exe)
      working-directory: ./autohdr_client_exe
      run: |
        pyinstaller main.spec --clean

    - name: Lưu trữ và gửi file cài đặt về cho bạn
      uses: actions/upload-artifact@v4
      with:
        name: Autohdr-Client-Windows-EXE
        path: autohdr_client_exe/dist/download_hdr.exe
        retention-days: 30 # Lưu trữ file trên nhánh Github của bạn trong 30 ngày
